/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminGovernanceRouteImport } from './routes/admin.governance'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminTablesRouteImport } from './routes/admin.tables'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as TableTableNumberRouteImport } from './routes/table.$tableNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGovernanceRoute = AdminGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableNumberRoute = TableTableNumberRouteImport.update({
  id: '/table/$tableNumber',
  path: '/table/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/my-orders': typeof MyOrdersRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/my-orders': typeof MyOrdersRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/my-orders': typeof MyOrdersRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/login'
    | '/menu'
    | '/my-orders'
    | '/owner'
    | '/profile'
    | '/scanner'
    | '/settings'
    | '/signup'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/governance'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/order/$orderId'
    | '/table/$tableNumber'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/login'
    | '/menu'
    | '/my-orders'
    | '/owner'
    | '/profile'
    | '/scanner'
    | '/settings'
    | '/signup'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/governance'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/order/$orderId'
    | '/table/$tableNumber'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/login'
    | '/menu'
    | '/my-orders'
    | '/owner'
    | '/profile'
    | '/scanner'
    | '/settings'
    | '/signup'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/governance'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/order/$orderId'
    | '/table/$tableNumber'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  MyOrdersRoute: typeof MyOrdersRoute
  OwnerRoute: typeof OwnerRoute
  ProfileRoute: typeof ProfileRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  TableTableNumberRoute: typeof TableTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/governance': {
      id: '/admin/governance'
      path: '/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AdminGovernanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNumber': {
      id: '/table/$tableNumber'
      path: '/table/$tableNumber'
      fullPath: '/table/$tableNumber'
      preLoaderRoute: typeof TableTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminGovernanceRoute: typeof AdminGovernanceRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminGovernanceRoute: AdminGovernanceRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  MyOrdersRoute: MyOrdersRoute,
  OwnerRoute: OwnerRoute,
  ProfileRoute: ProfileRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  TableTableNumberRoute: TableTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
